services:
  mariadb:
    build: ./mariadb/
    image: ismailenniou/mr:v1.0
    ports:
      - target: 3306
        published: 3306
    networks:
      - counter-net
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: on-failure
    secrets:
      - db_password
      - db_root_password

  nginx:
    build: ./nginx/
    image: ismailenniou/nginx:v1.0
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    networks:
      - counter-net
    depends_on:
      - mariadb
    restart: on-failure

networks:
  counter-net:

volumes:
  mariadb_data:

secrets:
  db_password:
    file: ../../secrets/db_password.txt
  db_root_password:
    file: ../../secrets/db_root_password.txt
