services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    image: ismailenniou/mariadb:v1.0
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - /home/ien-niou/data/mariadb_data:/var/lib/mysql
    restart: on-failure
    secrets:
      - db_password
      - db_root_password
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}

  wordpress:
    build: ./wordpress
    container_name: wordpress
    image: ismailenniou/wordpress:v1.0
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - /home/ien-niou/data/wordpress_data:/var/www/wordpress
    ports:
      - "9000:9000"
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      DOMAIN_NAME: ${DOMAIN_NAME}
    secrets:
      - db_password
      - wp_admin_password
    restart: on-failure

  nginx:
    build: ./nginx
    container_name: nginx
    image: ismailenniou/nginx:v1.0
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    restart: on-failure
    volumes:
      - /home/ien-niou/data/wordpress_data:/var/www/wordpress
    environment:
      NGINX_HOST: ${DOMAIN_NAME}
      NGINX_PORT: ${NGINX_PORT}

  redis:
    build: ./bonus/redis/
    container_name: redis
    image: ismailenniou/redis:v1.0
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: on-failure
    volumes:
      - /home/ien-niou/data/redis_data:/data

  ftp:
    build: ./bonus/ftp/
    container_name: ftp
    image: ismailenniou/ftp:v1.0
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    networks:
      - inception
    restart: on-failure
    volumes:
      - /home/ien-niou/data/wordpress_data:/var/www/wordpress
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASSWORD: ${FTP_PASSWORD}

  adminer:
    build: ./bonus/adminer/
    container_name: adminer
    image: ismailenniou/adminer:v1.0
    networks:
      - inception
    depends_on:
      - mariadb
    ports:
      - "8080:8088"

  portfolio:
    build: ./bonus/static/
    container_name: portfolio
    image: ismailenniou/portfolio:v1.0
    ports:
      - "8085:80"
    networks:
      - inception
    restart: on-failure

  portainer:
    container_name: portainer
    image: portainer:1337.42
    build: ./bonus/portainer
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - inception
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
  wordpress_data:
  redis_data:

secrets:
  db_password:
    file: ../../secrets/db_password.txt
  db_root_password:
    file: ../../secrets/db_root_password.txt
  wp_admin_password:
    file: ../../secrets/wp_admin_password.txt
  mariadb_root_password:
    file: ../../secrets/mariadb_root_password.txt
