services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    image: ismailenniou/mariadb:v1.0
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: on-failure
    secrets:
      - db_password
      - db_root_password
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wpuser

  wordpress:
    build: ./wordpress
    container_name: wordpress
    image: ismailenniou/wordpress:v1.0
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress
    ports:
      - "9000:9000"
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wpuser
      DOMAIN_NAME: https://ien-niou.42.fr
    secrets:
      - db_password
      - wp_admin_password
    restart: on-failure

  nginx:
    build: ./nginx
    container_name: nginx
    image: ismailenniou/nginx:v1.0
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    restart: on-failure
    volumes:
      - wordpress_data:/var/www/wordpress

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
  wordpress_data:

secrets:
  db_password:
    file: ../../secrets/db_password.txt
  db_root_password:
    file: ../../secrets/db_root_password.txt
  wp_admin_password:
    file: ../../secrets/wp_admin_password.txt
  mariadb_root_password:
    file: ../../secrets/mariadb_root_password.txt
